#!/usr/bin/env bash

# Add functionality by creating a module under the modules directory.
# Also, perhaps take a look at https://github.com/progrium/bashstyle


if [[ "$BASH_VERSINFO" -lt "4" ]]; then
	echo "!! Your system Bash is out of date: $BASH_VERSION"
	echo "!! Please upgrade to Bash 4 or greater."
	if [[ "$(uname)" == "Darwin" ]]; then
		echo
		echo "On OS X, use Homebrew to install latest Bash:"
		echo '   $ brew install bash'
		echo
		echo "Then add it to /etc/shells and change your user's shell:"
		echo '   $ sudo sh -c "echo /usr/local/bin/bash >> /etc/shells"'
		echo '   $ chsh -s /usr/local/bin/bash'
		echo
		echo "A new terminal session is then necessary to take effect."
		echo
	fi
	exit 2
fi

if [[ "$(base64 --version)" == "Version DEBUG" ]]; then
	echo "!! You have a faulty version of base64 in your PATH"
	echo "!! Quickest solution would be to use Homebrew:"
	echo '    $ brew install base64'
	echo
	exit 2
fi

main() {
	set -eo pipefail; [[ "$TRACE" ]] && set -x
	cd "$(dirname $BASH_SOURCE)"
	for module in ./modules/*.bash; do
		source "$module"
	done
	cmd-ns "" "$@"
}

[[ "$0" == "$BASH_SOURCE" ]] && main "$@"
